backend:
  name: github
  repo: nhlp/alpekhukuk-site
  branch: main
  base_url: https://www.alpekhukuk.com.tr
  auth_endpoint: /api/auth

local_backend: false

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Makaleler"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "makaleler/{{ slug }}/"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Özet", name: "description", widget: "text", required: false }
      - {
          label: "Tarih",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          time_format: false,
        }
      - {
          label: "Yazar",
          name: "author",
          widget: "string",
          default: "Alpek Hukuk",
        }
      - { label: "Etiketler", name: "tags", widget: "list", default: ["hukuk"] }
      - {
          label: "Hero Görseli",
          name: "hero",
          widget: "image",
          required: false,
        }
      - { label: "İçerik", name: "body", widget: "markdown" }
